### ISSUE TITLE
C23 feature support checklist

### ISSUE THREAD

**Issue by Vexu** [Vexu/arocc#430]
Based on https://en.cppreference.com/w/c/23

- [x] `_Static_asert` with no message
- [x] `[[nodiscard]]`
- [x] `[[maybe_unused]]`
- [x] `[[deprecated]]`
- [x] Attributes
~~- [ ] IEEE 754 decimal floating-point types~~
    - #552
- [x] `[[fallthrough]]`
- [x] u8 character constants
- [x] Removal of function definitions without prototype
- [x] `[[nodiscard]]` with message
- [x] Unnamed parameters in function definitions
- [x] Labels before declarations and end of blocks
- [x] Binary integer constants
- [x] `__has_c_attribute` in preprocessor conditionals
- [x] `__has_c_attribute(vendor::attribute)` 
- [x] Allow duplicate attributes
~~- [ ] IEEE 754 interchange and extended types~~
    - #552
- [x] Digit separators
- [x] #elifdef and #elifndef
- [x] Type change of u8 string literals
- [x] `[[maybe_unused]]` for labels
- [x] `#warning`
- [x] Bit-precise integer types (`_BitInt`)
- [x] `[[noreturn]]`
- [x] Suffixes for bit-precise integer constants
- [x] `__has_include` in preprocessor conditionals
- [x] Removal of function declarations without prototype
- [x] Empty initializers
- [x] typeof ...
- [x] ... and typeof_unqual
- [x] New spelling of keywords
- [x] Predefined true and false
- [x] `[[unsequenced]]`
- [x] `[[reproducible]]`
- [x] Relax requirements for variadic parameter list
- [x] Type inference in object definitions (`auto`)
- [x] constexpr objects
- [x] nullptr
- [x] `#embed`
- [x] `#embed` parameters `limit`, `suffix`, `prefix`, `if_empty`
- [x] `__has_embed`
- [x] Storage-class specifiers for compound literals 
- [x] `__VA_OPT__`
- [x] Identifier Syntax using Unicode Standard Annex 31
- [x] Check identifier NFC normalized
- [x] Type change of u8 string literals
- [x] u8 character constants (already implemented, should be an error for older versions)

**Comment by ehaas** [comment]
This list may also be helpful for test cases: https://htmlpreview.github.io/?https://icube-forge.unistra.fr/icps/c23-library/-/raw/main/README.html

**Comment by Vexu** [comment]
@ehaas Do you want to handle the Unicode identifier change?

**Comment by ehaas** [comment]
Sure. The list of acceptable start/continuation characters should be straightforward.  I've never done anything with unicode normalization so I don't know how much work that will be, but I think it will fit nicely with the string interner and there won't be too much incidental complexity around adding it.
