### ISSUE TITLE
`resinator` tracking issue

### ISSUE THREAD

**Issue by squeek502** [Vexu/arocc#509]
As part of https://github.com/ziglang/zig/issues/16270, [resinator](https://github.com/squeek502/resinator) will eventually want to be able to use `aro` as its preprocessor.

This issue contains a list of everything that I'm aware of that currently blocks `aro` from having parity with `clang` as a preprocessor for `resinator`:

- [x] https://github.com/Vexu/arocc/issues/508
- [x] Support for Windows-1252 encoded files
  + Example (the `©` character): https://github.com/microsoft/Windows-classic-samples/blob/ac06e54a15e9a62443e400fffff190fb978ea586/Samples/Win7Samples/multimedia/gdi/printer/Printer.Rc#L142
  + Currently errors with `.\Printer.Rc:0:32: error: source file is not valid UTF-8`
  + Note: encoding should be preserved through preprocessing
- [x] Support for outputting line directives (ideally outputted as e.g. `#line 5` instead of `# 5`)
  + This is needed because `resinator` needs to be able to know which lines came from which file (the source from `#include`d `.h` files needs to be ignored, among other things)
  + `clang` outputs `# <num>` by default and puts outputting `#line <num>` instead of `# <num>` behind a `-fuse-line-directives` flag
- [x] Support for `\` as a path separator in `#include`s
  + Example: https://github.com/microsoft/Windows-classic-samples/blob/ac06e54a15e9a62443e400fffff190fb978ea586/Samples/Win7Samples/multimedia/directshow/misc/dmoenum/DMOEnum.rc#L244
- [x] Option to keep comments intact during preprocessing (`clang` has the `--comments` flag)
  + This is low-priority, it's only useful for emulating how comments are removed by the rc.exe preprocessor in certain edge cases
- [x] Support for `#include` search paths relative to the 'root' source file (unsure if there's a correct term for this)
  + Example: https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/Win7Samples/dataaccess/oledb/rowsetviewer
    + `rowsetviewer.rc` includes `res/rowsetviewer.rc2` which in turn includes `version.h` which is relative to `rowsetviewer.rc`
  + Clang behavior when target ABI is `msvc` or `-fms-compatibility` is set (this is what `arocc` should have support for in some fashion):
    > ```
    > In file included from test.rc:1:
    > ./sub/sub.rc:1:10: warning: #include resolved using non-portable Microsoft search rules as: ./include.h [-Wmicrosoft-include]
    >     1 | #include "include.h"
    >       |          ^
    > ```
    > (successful compilation)
  + Clang behavior when target ABI is `gnu` and `-fms-compatibility` is not set (this matches `arocc`'s current behavior):
    > ```
    > ./sub/sub.rc:1:10: fatal error: 'include.h' file not found
    >    1 | #include "include.h"
    >      |          ^~~~~~~~~~~
    > ```
    > (error)
  + Minimal test case (`arocc -E --emulate=msvc test.c` should run without error):
    - `./test.c` with `#include "sub/sub.h"`
    - `./sub/sub.h` with `#include "relative.h"`
    - `./relative.h` can be empty
- [x] The `SUB` character (`0x1A`) is (for who-knows-what reason) at the end of certain `.rc` files in the Windows-classic-samples set. I'm not sure if there's a 'correct' thing to do with this, but both clang and the `rc.exe` preprocessor treat it as something like an EOF marker:

  ```c
  foo

  <0x1A>

  bar
  ```
  only results in `foo` after preprocessing--everything after the `<0x1A>` byte is ignored.
  + Example: https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/Win7Samples/winbase/winnt/perftool/perfdlls/appmem/perfdll/Perfmem.Rc
  + (as a fun caveat, certain placements of a `<0x1A>` byte will cause `rc.exe` to loop infinitely, e.g. `1 MENUEX FIXED<0x1A>VERSION`; the Windows-classic-samples only have `<0x1A>` at the end of the file)

---

Current status when running https://github.com/squeek502/win32-samples-rc-tests with `aro` as the preprocessor for `resinator`:

```
83 .rc files processed with discrepancies
different .res outputs:     0
unexpected compile errors:  83
missing compile errors:     0

402 .rc files processed without discrepancies
identical .res outputs:     377
expected compile errors:    25
```

Expected results:

```
485 .rc files processed without discrepancies
identical .res outputs:     460
expected compile errors:    25
```

**Comment by squeek502** [comment]
New problem added to OP that I missed initially:

- The `SUB` character (`0x1A`) is (for who-knows-what) reason at the end of certain `.rc` files in the Windows-classic-samples set. I'm not sure if there's a 'correct' thing to do with this, but both clang and the `rc.exe` preprocessor treat it as something like an EOF marker:

  ```c
  foo

  <0x1A>

  bar
  ```
  only results in `foo` after preprocessing--everything after the `<0x1A>` byte is ignored.
  + Example: https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/Win7Samples/winbase/winnt/perftool/perfdlls/appmem/perfdll/Perfmem.Rc
  + (as a fun caveat, certain placements of a `<0x1A>` byte will cause `rc.exe` to loop infinitely, e.g. `1 MENUEX FIXED<0x1A>VERSION`; the Windows-classic-samples only have `<0x1A>` at the end of the file)

**Comment by Vexu** [comment]
Cursed, relevant code from clang:
```c++
case 26:  // DOS & CP/M EOF: "^Z".
  // If we're in Microsoft extensions mode, treat this as end of file.
  if (LangOpts.MicrosoftExt) {
    if (!isLexingRawMode())
      Diag(CurPtr-1, diag::ext_ctrl_z_eof_microsoft);
    return LexEndOfFile(Result, CurPtr-1);
  }

  // If Microsoft extensions are disabled, this is just random garbage.
  Kind = tok::unknown;
  break;
```
